delays:
  after_click: 1.0
  after_date: 1.0
  after_input: 1.0
  after_item_code: 2.0
  after_nit: 2.0
  after_order: 1.0
  after_quantity: 2.0
  after_tab: 0.5
  long: 2.0
  medium: 1.0
  navigation_wait: 2.0
  sap_double_click: 10.0
  sap_startup: 25.0
  screenshot_wait: 1.0
  short: 0.5
  very_long: 3.0
  very_short: 0.1
  window_activation: 2.0
development:
  debug_screenshot_path: ./debug_screenshots
  enable_debug_screenshots: false
  enable_detailed_logging: false
  enable_performance_metrics: true
files:
  exclude_prefixes:
  - .
  - desktop.ini
  exclude_suffixes:
  - .tmp
  valid_extensions:
  - .json
google_drive:
  enabled: true
  folder_id: 17zOU8KlONbkfzvEyHRcXx9IvhUA7-dKv
  upload_original_files: true
  upload_screenshots: false
logging:
  backup_count: 3
  error_backup_count: 2
  error_file_size: 2097152
  level: INFO
  log_dir: logs
  max_file_size: 5242880
messages:
  next_execution: Proceso RPA completado, esperando próxima ejecución en 10 minutos
  system_active: Sistema RPA activo. Presiona Ctrl+C para detener.
  system_monitoring: Sistema RPA en espera - monitoreando nuevos archivos JSON...
  system_startup: === SISTEMA RPA TAMAPRINT ===
  system_stopped: Sistema RPA detenido por el usuario.
navigation:
  tabs_after_date: 4
  tabs_after_last_quantity: 1
  tabs_after_nit: 3
  tabs_after_order: 4
  tabs_after_quantity_next_item: 3
  tabs_before_quantity: 2
ocr:
  easyocr_gpu: false
  easyocr_languages:
  - en
  tesseract_config: --oem 3 --psm 6
  tesseract_path: C:\Program Files\Tesseract-OCR\tesseract.exe
  totales_keywords:
  - Total antes del descuento
  - Descuento
  - Gastos adicionales
  - Redondeo
  - Impuesto
  - Total del documento
  - Total antes
  - Total documento
paths:
  data_json: ./data/outputs_json
  inserted_orders: ./rpa/vision/reference_images/inserted_orders
  processed_json: ./data/outputs_json/Procesados
  reference_images: ./rpa/vision/reference_images
  remote_desktop: ./rpa/vision/reference_images/remote_desktop.png
  sap_desktop: ./rpa/vision/reference_images/sap_desktop.png
  sap_order_template: ./rpa/vision/reference_images/sap_orden_de_ventas_template.png
  template_image: ./rpa/vision/reference_images/template.png
retries:
  max_remote_desktop_attempts: 3
  max_sap_open_attempts: 3
  retry_delay: 5
system:
  error_recovery_wait: 20
  main_loop_interval: 10
  schedule_interval: 10
template_matching:
  agregar_y_button:
    anti_error_confidence: 0.7
    fallback_confidence: 0.75
    margin_from_edge: 12
    primary_confidence: 0.85
    search_region_height_ratio: 0.25
    search_region_width_ratio: 0.33
  default_confidence: 0.8
  high_confidence: 0.9
  low_confidence: 0.5
  sap_icon_confidence: 0.7
  scrollbar_confidence: 0.8
  timeout: 10.0
windows:
  activation_timeout: 2.0
  maximize_wait: 0.5
  remote_desktop: 20.96.6.64 - Conexión a Escritorio remoto
